### ISSUE TITLE
Can't compile the ppd file

### ISSUE THREAD

**Issue by odinblister** [ofosos/scratch#4]
I'm trying to follow your instructions to create the remarkable ppd file.  However, the output of `ppdc remarkable.drv` gives the following error: 
`ppdc: Unknown token "<!DOCTYPE html>" seen on line 8 of remarkable.drv.`

Any ideas?

**Comment by ofosos** [comment]
You probably did download the HTML marked up page from github, not the raw content.

**Comment by odinblister** [comment]
Doh!  That was indeed the problem.  Thanks.
