### ISSUE TITLE
Problem on compiling

### ISSUE THREAD

**Issue by vchryssos** [ofosos/scratch#9]
Hi there. Great work you've done with the reMarkable reading flow. I was looking for something like this for a long time. Thank you so much for sharing! 

When applying the `ppdc remarkable.drv` command I get the following error: 
`ppdc: Unknown token "<!DOCTYPE html>" seen on line 7 of remarkable.drv`

Any help with this is highly appreciated! 
Thank you in advance for your time.
V.

**Comment by ofosos** [comment]
Go to the file on github, click on the raw button, click on save as. Don't save the HTML rendering of the file.

**Comment by vchryssos** [comment]
> Go to the file on github, click on the raw button, click on save as. Don't save the HTML rendering of the file.

Thank you for this! I manged to go over the compilation hurdle.. Really appreciate it.
